api = "0.7"

[buildpack]
id = "google.ruby.functions-framework"
version = "0.9.1"
name = "Ruby - Functions Framework"

[[stacks]]
id = "openfunction.ruby26"

[[stacks]]
id = "google.ruby26"

[[stacks]]
id = "google.ruby27"
