api = "0.7"

[buildpack]
id = "google.java.clear_source"
version = "0.9.0"
name = "Java - Clear Source"

[[stacks]]
id = "google"

[[stacks]]
id = "openfunction.java11"

[[stacks]]
id = "openfunction.java16"

[[stacks]]
id = "openfunction.java17"

[[stacks]]
id = "openfunction.java18"