api = "0.7"

[buildpack]
id = "google.php.functions-framework"
version = "0.9.4"
name = "Google - PHP - Functions Framework"

[[stacks]]
id = "google"

[[stacks]]
id = "google.php73"

[[stacks]]
id = "google.php74"
