description = "Ubuntu 18 base image with buildpacks for Nodejs"

[[buildpacks]]
  id = "google.config.entrypoint"
  uri = "entrypoint.tgz"

[[buildpacks]]
  id = "openfunction.nodejs.npm"
  uri = "nodejs/npm.tgz"

[[buildpacks]]
  id = "openfunction.nodejs.yarn"
  uri = "nodejs/yarn.tgz"

[[buildpacks]]
  id = "openfunction.nodejs.functions-framework"
  uri = "nodejs/functions_framework.tgz"

[[buildpacks]]
  id = "google.utils.label"
  uri = "label.tgz"

###########
# Node.js #
###########
# Note: We detect Node.js last because client-side .js files exist in many
# web projects and detecting Node.js last will decrease the chance of
# detection confusion.

[[order]]
  [[order.group]]
    id = "openfunction.nodejs.yarn"

  [[order.group]]
    id = "openfunction.nodejs.functions-framework"
    optional = true

  [[order.group]]
    id = "google.config.entrypoint"
    optional = true

  [[order.group]]
    id = "google.utils.label"

[[order]]
  [[order.group]]
    id = "openfunction.nodejs.npm"

  [[order.group]]
    id = "openfunction.nodejs.functions-framework"
    optional = true

  [[order.group]]
    id = "google.config.entrypoint"
    optional = true

  [[order.group]]
    id = "google.utils.label"

# Separate groups for Node.js projects without dependencies.
# Making both yarn and npm optional in the previous groups leads
# the yarn group to opt in every time.

# Node.js functions without a package.json.
[[order]]
  [[order.group]]
    id = "openfunction.nodejs.functions-framework"

  [[order.group]]
    id = "google.config.entrypoint"
    optional = true

  [[order.group]]
    id = "google.utils.label"

# Currently built with //builders/node16/stack/stack:build.
[stack]
  id = "openfunction.node16"
  build-image = "openfunctiondev/buildpacks-node16-build:v1"
  run-image = "openfunctiondev/buildpacks-node16-run:v1"

[lifecycle]
  version = "0.13.2"
