api = "0.6"

[buildpack]
id = "google.dotnet.publish"
version = "0.9.0"
name = ".NET - Publish"

# The cloud run source deploy command uses pack. Older versions of pack which
# were distributed by gcloud for cloud run do not support wildcard stack id
# matching. For that reason we must allow an explicit stack id of 'google'
[[stacks]]
id = "google"

[[stacks]]
id = "*"