api = "0.7"

[buildpack]
id = "google.go.clear_source"
version = "0.9.0"
name = "Go - Clear Source"

[[stacks]]
id = "google"

[[stacks]]
id = "openfunction.go115"

[[stacks]]
id = "openfunction.go116"