description = "Ubuntu 18 base image with buildpacks for Python"

[[buildpacks]]
  id = "google.config.entrypoint"
  uri = "entrypoint.tgz"

[[buildpacks]]
  id = "google.python.pip"
  uri = "python/pip.tgz"

[[buildpacks]]
  id = "google.python.functions-framework"
  uri = "python/functions_framework.tgz"

[[buildpacks]]
  id = "google.python.missing-entrypoint"
  uri = "python/missing_entrypoint.tgz"

[[buildpacks]]
  id = "google.utils.label"
  uri = "label.tgz"

##############
# Python 1/2 #
##############

# Python functions.
[[order]]
  [[order.group]]
    id = "google.python.functions-framework"

  [[order.group]]
    id = "google.python.pip"
    optional = true

  [[order.group]]
    id = "google.config.entrypoint"
    optional = true

  [[order.group]]
    id = "google.utils.label"

##############
# Python 2/2 #
##############

# This buildpack group will always fail but with a clear message that the
# entrypoint is missing. It must be the last group otherwise projects with
# a single .py file and no entrypoint will fail
[[order]]
  [[order.group]]
    id = "google.python.missing-entrypoint"

  [[order.group]]
    id = "google.utils.label"

# Currently built with //builders/py37/stack/stack:build.
[stack]
  id = "google"
  build-image = "openfunctiondev/buildpacks-py37-build:v1"
  run-image = "openfunctiondev/buildpacks-py37-run:v1"

[lifecycle]
  version = "0.13.2"
