api = "0.7"

[buildpack]
id = "google.nodejs.npm-gcp-build"
version = "0.9.0"
name = "Node.js - NPM gcp-build"

[[stacks]]
id = "google.nodejs10"

[[stacks]]
id = "google.nodejs12"

[[stacks]]
id = "google.nodejs14"

[[stacks]]
id = "google.nodejs16"