api = "0.7"

[buildpack]
id = "google.python.functions-framework-compat"
version = "0.9.2"
name = "Python - Functions Framework (compatibility)"

[[stacks]]
id = "google"

[[stacks]]
id = "google.python37"
