api = "0.7"

[buildpack]
id = "google.nodejs.appengine"
version = "0.9.0"
name = "Node.js - App Engine"

[[stacks]]
id = "google.nodejs10"

[[stacks]]
id = "google.nodejs12"

[[stacks]]
id = "google.nodejs14"

[[stacks]]
id = "google.nodejs16"
