api = "0.7"

[buildpack]
id = "openfunction.java.gradle"
version = "0.9.0"
name = "Java - Gradle"

[[stacks]]
id = "openfunction"

[[stacks]]
id = "openfunction.java11"

[[stacks]]
id = "openfunction.java16"

[[stacks]]
id = "openfunction.java17"

[[stacks]]
id = "openfunction.java18"