api = "0.7"

[buildpack]
id = "google.ruby.bundle"
version = "0.9.0"
name = "Ruby - Bundle"

[[stacks]]
id = "openfunction.ruby26"

[[stacks]]
id = "google.ruby25"

[[stacks]]
id = "google.ruby26"

[[stacks]]
id = "google.ruby27"
