api = "0.7"

[buildpack]
id = "openfunction.java.functions-framework"
version = "1.0.0"
name = "Java - Functions Framework"

[[stacks]]
id = "openfunction"

[[stacks]]
id = "openfunction.java11"

[[stacks]]
id = "openfunction.java16"

[[stacks]]
id = "openfunction.java17"

[[stacks]]
id = "openfunction.java18"
